// tutorial-babel-vue/src/components/SubComponent.vue
<template>
  <div>
    <h2>{{message}}</h2>
    <p>{{count}}</p>
    <p>
      <button @click="onClick">Add +1</button>
    </p>
  </div>
</template>

<script>
  export default {
    name: 'sub-component',

    data(){
      return {
        count: 0
      }
    },
    props: ['message'],

    methods: {
      onClick() {
        console.log('クリックされました');
        this.count = this.count + 1;
      }
    }
  };
</script>

<style scoped>
  h2 {
    font-weight: normal;
    font-size: 1.25rem;
  }
</style>

// tutorial-typescript-react/src/sub-component.tsx
import * as React from 'react';
import {useCallback, useState} from "react";

// Propsの型定義
interface IProps {
    name: string;
}

export const SubComponent: React.FC<IProps> = (props) => {

    const [count, setCount] = useState(0)
    const handleClick = useCallback(() => {
      console.log('クリックされました');
        setCount(count + 1)
    }, [count])

    return (
        <div>
            <h2>{props.name}</h2>
            <div>{count}</div>
            <button onClick={handleClick}>Add +1</button>
        </div>
    );
}
