// tutorial-babel-react/src/sub-component.js
import React from "react";

export class SubComponent extends React.Component {
  constructor() {
    super();
    this.state = {
      count: 0,
    };
  }

  handleClick() {
    console.log("クリックされました");
    this.setState({
      count: this.state.count + 1,
    });
  }

  render() {
    return (
      <div>
        <h2>{this.props.name}</h2>
        <div>{this.state.count}</div>
        <button onClick={this.handleClick.bind(this)}>Add +1</button>
      </div>
    );
  }
}

// tutorial-babel-vue/src/components/SubComponent.vue
<template>
  <div>
    <h2>{{message}}</h2>
    <p>{{count}}</p>
    <p>
      <button @click="onClick">Add +1</button>
    </p>
  </div>
</template>

<script>
  export default {
    name: 'sub-component',

    data(){
      return {
        count: 0
      }
    },
    props: ['message'],

    methods: {
      onClick() {
        console.log('クリックされました');
        this.count = this.count + 1;
      }
    }
  };
</script>

<style scoped>
  h2 {
    font-weight: normal;
    font-size: 1.25rem;
  }
</style>
